src/objects/ZV_Board__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>ZV_Game__c</referenceTo>
        <relationshipLabel>Boards</relationshipLabel>
        <relationshipName>Boards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board</label>
    <nameField>
        <displayFormat>ZVB-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Board Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Cell__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>ZV_Board__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZV_GamePlayer__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>ZV_Game__c</referenceTo>
        <relationshipLabel>Game Players</relationshipLabel>
        <relationshipName>Game_Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game Player</label>
    <nameField>
        <displayFormat>ZVGP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <displayFormat>ZVP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_GameCellContext.cls
public class ZV_GameCellContext {
	ZV_BoardSelector boardSelector;
	ZV_CellSelector cellSelector;
	ZV_GameSelector gameSelector;
	ZV_GamePlayerSelector gamePlayerSelector;
	ZV_PlayerSelector playerSelector;
	ZV_UserInfoWrapper userInfoWrapper;

	public ZV_GameCellContext(
			Id cellId,
			ZV_BoardSelector boardSelector,
			ZV_CellSelector cellSelector,
			ZV_GameSelector gameSelector,
			ZV_GamePlayerSelector gamePlayerSelector,
			ZV_PlayerSelector playerSelector,
			ZV_UserInfoWrapper userInfoWrapper
		) {
		this.cellId = cellId;
		this.boardSelector = boardSelector;
		this.cellSelector = cellSelector;
		this.gameSelector = gameSelector;
		this.gamePlayerSelector = gamePlayerSelector;
		this.playerSelector = playerSelector;
		this.userInfoWrapper = userInfoWrapper;
	}		

	public ZV_GameCellContext(Id cellId) {
		this(
			cellId,
			new ZV_BoardSelector(), 
			new ZV_CellSelector(), 
			new ZV_GameSelector(), 
			new ZV_GamePlayerSelector(), 
			new ZV_PlayerSelector(),
			new ZV_UserInfoWrapper()
		);
	}	
	
    @testVisible public ZV_Board__c board {
		get {
			if (this.board == null) {
				this.board = this.boardSelector.selectById(new Set<Id>{this.boardId})[0];
			}
			return this.board;
		} 
		private set;
	} 
    
    @testVisible public Id boardId {
		get {
			if (this.boardId == null) {
				this.boardId = this.cell.Board__c;
			}
			return this.boardId;
		} 
		private set;
	} 
	
    @testVisible public ZV_Cell__c cell {
		get {
			if (this.cell == null) {
				this.cell = this.cellSelector.selectById(new Set<Id>{this.cellId})[0];
			}
			return this.cell;
		} 
		private set;
	} 

    @testVisible public Id cellId {get; private set;}
	
    @testVisible public ZV_Game__c game {
		get {
			if (this.game == null) {
				this.game = this.gameSelector.selectById(new Set<Id>{this.gameId})[0];
			}
			return this.game;
		} 
		private set;
	} 
    
    @testVisible public Id gameId {
		get {
			if (this.gameId == null) {
				this.gameId = board.Game__c;
			}
			return this.gameId;
		} 
		private set;
	} 

    @testVisible public List<ZV_GamePlayer__c> gamePlayerList {
		get {
			if (this.gamePlayerList == null) {
				this.gamePlayerList = this.gamePlayerSelector.selectByGameId(this.gameId);
			}
			return this.gamePlayerList;
		} 
		private set;
	}

    @testVisible public List<ZV_Player__c> playerList {
		get {
			if (this.playerList == null) {
				this.playerList = this.playerSelector.selectFor(this.gamePlayerList);
			}
			return this.playerList;
		} 
		private set;
	}
	
	@testVisible public Id userId {
		get {
			if (this.userId == null) {
				this.userId = this.userInfoWrapper.userId;
			}
			return this.userId;
		} 
		private set;
	} 
}