src/objects/ZV_Board__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>ZV_Game__c</referenceTo>
        <relationshipLabel>Boards</relationshipLabel>
        <relationshipName>Boards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Height</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Width</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Board</label>
    <nameField>
        <displayFormat>ZVB-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Board Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_BoardService.cls
public with sharing class ZV_BoardService {
	private static Integer DEFAULT_BOARD_HEIGHT = 3;
	private static Integer DEFAULT_BOARD_WIDTH = 3;
		
    public List<ZV_Board__c> createBoards(List<ZV_Game__c> gameList) {
    	List<ZV_Board__c> boardList = new List<ZV_Board__c>();
    	for (ZV_Game__c game : gameList) {
    		boardList.add(new ZV_Board__c(
    			Game__c = game.id,
    			Height__c = DEFAULT_BOARD_HEIGHT,
    			Width__c = DEFAULT_BOARD_WIDTH
    		));
    	}
    	return boardList; 
    }
}