src/objects/ZV_Board__c.object
<CustomObject>
    <label>Board</label>
    <nameField>
        <displayFormat>ZVB-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Board Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Stalemate</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZV_GamePlayer__c.object
<CustomObject>
    <label>Game Player</label>
    <nameField>
        <displayFormat>ZVGP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <displayFormat>ZVP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_BoardAuraCtrl.cls
public class ZV_BoardAuraCtrl {
	F45_DML_GenericDml genericDml; 
	ZV_BoardSelector boardSelector;
	ZV_GamePlayerSelector gamePlayerSelector;
	ZV_RecordTypeCache recordTypeCache;   
	ZVG_GameLookup gameLookup;
	 
	public ZV_BoardAuraCtrl(
			F45_DML_GenericDml genericDml,
			ZV_BoardSelector boardSelector, 
			ZV_GamePlayerSelector gamePlayerSelector,
			ZV_RecordTypeCache recordTypeCache, 
			ZVG_GameLookup gameLookup
		) {
		this.genericDml = genericDml;
		this.boardSelector = boardSelector;
		this.gamePlayerSelector = gamePlayerSelector;
		this.recordTypeCache = recordTypeCache;
		this.gameLookup = gameLookup;
	} 

	public ZV_BoardAuraCtrl() {
		this(
			new F45_DML_GenericDml(), 
			new ZV_BoardSelector(), 
			new ZV_GamePlayerSelector(), 
			new ZV_RecordTypeCache(), 
			new ZVG_GameLookup()
		);
	}
	
    @AuraEnabled
    public static ZV_Board__c getBoard (Id boardId) {
    	return (new ZV_BoardAuraCtrl()).selectWithCells(boardId);
    }
    
    public ZV_Board__c selectWithCells (Id boardId) {
    	this.recordTypeCache.registerRequired(new Set<SObjectType>{
    		ZV_Game__c.SObjectType,
    		ZV_Player__c.SObjectType 
    	});
    	
    	ZV_GameContext gameContext = new ZV_GameContext(boardId);
    	if (gameContext.game.Status__c == 'New') {
    		this.gameLookup.getFor(gameContext.game).initializePlay(gameContext);
			this.genericDml.doUpsert(gameContext.updatedCellList);    	  
			this.genericDml.doUpdate(new List<ZV_Game__c>{gameContext.game});
    	} 
    	return gameContext.board;
    }
    
    @AuraEnabled
    public static List<ZV_GamePlayer__c> getPlayers (Id gameId) {
    	return (new ZV_CellContainerAuraCtrl()).selectGamePlayers(gameId);
    } 
    
    public List<ZV_GamePlayer__c> selectGamePlayers (Id gameId) {
    	return this.gamePlayerSelector.selectByGameId(gameId); 
    } 
}