src/objects/ZV_Board__c.object
<CustomObject>
    <fields>
        <fullName>Height__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Height</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Width</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Board</label>
    <nameField>
        <displayFormat>ZVB-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Board Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Cell__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>ZV_Board__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZV_CellService.cls
public with sharing class ZV_CellService {
    public List<ZV_Cell__c> createCells(List<ZV_Board__c> boardList) {
    	List<ZV_Cell__c> cellList = new List<ZV_Cell__c>();
    	for (ZV_Board__c board : boardList) {
    		for (Integer i = 1; i <= board.Width__c; i++) {
	    		for (Integer j = 1; j <= board.Height__c; j++) {
	    			cellList.add(new ZV_Cell__c(
	    				Board__c = board.id,
	    				X__c = i,
	    				Y__c = j
	    			));
	    		}
    		}
    	}
    	return cellList; 
    } 
}