src/objects/ZV_Board__c.object
<CustomObject>
    <fields>
        <fullName>Height__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Height</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Width</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Board</label>
    <nameField>
        <displayFormat>ZVB-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Board Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Cell__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>ZV_Board__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZV_BoardSelector.cls
public with sharing class ZV_BoardSelector extends fflib_SObjectSelector {
	ZV_CellSelector cellSelector;
	
	public ZV_BoardSelector(ZV_CellSelector cellSelector) {
		this.cellSelector = cellSelector;
	}

	public ZV_BoardSelector() {
		this(new ZV_CellSelector());
	}
	
	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
			ZV_Board__c.Id,
			ZV_Board__c.Height__c,
			ZV_Board__c.Width__c 
		};
	}

	public Schema.SObjectType getSObjectType() {
		return ZV_Board__c.sObjectType;
	} 

	public List<ZV_Board__c> selectById(Set<Id> idSet) {
		return (List<ZV_Board__c>) selectSObjectsById(idSet);
	}

	public List<ZV_Board__c> selectWithCells(Set<Id> idSet) {
		fflib_QueryFactory boardQueryFactory = newQueryFactory();
		fflib_QueryFactory cellQueryFactory = this.cellSelector.addQueryFactorySubselect(boardQueryFactory, 'Cells__r');
		return (List<ZV_Board__c>) Database.query(
			boardQueryFactory
				.setCondition('id in :idSet')
				.toSOQL()
		);
	}
}