src/objects/ZV_Cell__c.object
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Stalemate</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Winner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Winner</label>
        <referenceTo>ZV_Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_CellOccupyResult.cls
public class ZV_CellOccupyResult {
    @AuraEnabled public List<ZV_Cell__c> updatedCellList {get; private set;}
    @AuraEnabled public String gameStatus = 'In Progress';
    @AuraEnabled public Id gameWinner;
    
    public ZV_CellOccupyResult(List<ZV_Cell__c> updatedCellList, ZV_Game__c game) {
    	this.updatedCellList = updatedCellList;
    	this.gameStatus = game.Status__c;
    	this.gameWinner = game.Winner__c;
    } 
}