src/objects/ZV_Cell__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>ZV_Board__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZV_CellSelector.cls
public with sharing class ZV_CellSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
			ZV_Cell__c.Board__c,
			ZV_Cell__c.Id,
			ZV_Cell__c.Occupant__c,
			ZV_Cell__c.X__c,
			ZV_Cell__c.Y__c 
		};
	}

	public Schema.SObjectType getSObjectType() {
		return ZV_Cell__c.sObjectType;
	} 

	public override String getOrderBy() {
		return 'Y__c ASC, X__c ASC';
	}

	public List<ZV_Cell__c> selectById(Set<Id> idSet) {
		return (List<ZV_Cell__c>) selectSObjectsById(idSet);
	}
}