src/objects/ZV_Cell__c.object
<CustomObject>
    <label>Cell</label>
    <nameField>
        <displayFormat>ZVC-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Cell Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZV_GamePlayer__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>ZV_Game__c</referenceTo>
        <relationshipLabel>Game Players</relationshipLabel>
        <relationshipName>Game_Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PlayOrder__c</fullName>
        <label>Play Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>ZV_Player__c</referenceTo>
        <relationshipLabel>Game Players</relationshipLabel>
        <relationshipName>Game_Players</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game Player</label>
    <nameField>
        <displayFormat>ZVGP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ZV_Player__c.object
<CustomObject>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>ZVP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZVG_TraditionalTicTacToeGameVsComputer.cls
public class ZVG_TraditionalTicTacToeGameVsComputer implements ZVG_GameIntf {  
	ZV_GamePlayerService gamePlayerService;  
	ZV_PlayerService playerService;  
	ZV_Randomizer randomizer;
	ZVR_RobotPlayerHelper robotPlayerHelper;
	ZVSC_StalemateConditionHelper stalemateConditionHelper;
	ZVVC_VictoryConditionHelper victoryConditionHelper;
	
	public ZVG_TraditionalTicTacToeGameVsComputer(
			ZV_GamePlayerService gamePlayerService,
			ZV_PlayerService playerService, 
			ZV_Randomizer randomizer,
			ZVR_RobotPlayerHelper robotPlayerHelper, 
			ZVSC_StalemateConditionHelper stalemateConditionHelper,
			ZVVC_VictoryConditionHelper victoryConditionHelper
		) {
		this.gamePlayerService = gamePlayerService;
		this.playerService = playerService;
		this.randomizer = randomizer;
		this.robotPlayerHelper = robotPlayerHelper;
		this.stalemateConditionHelper = stalemateConditionHelper;
		this.victoryConditionHelper = victoryConditionHelper;
	}

	public ZVG_TraditionalTicTacToeGameVsComputer() {
		this(
			new ZV_GamePlayerService(),
			new ZV_PlayerService(), 
			new ZV_Randomizer(), 
			new ZVR_RobotPlayerHelper(),
			new ZVSC_StalemateConditionHelper(), 
			new ZVVC_VictoryConditionHelper()
		);
	}
 
	private static List<Type> VICTORY_CONDITION_LIST = new List<Type>{
		ZVVC_FullColumn.class,
		ZVVC_FullRow.class,
		ZVVC_LowerLeftCornerToUpperRightCorner.class,
		ZVVC_UpperLeftCornerToLowerRightCorner.class
	};

	private static List<Type> STALEMATE_CONDITION_LIST = new List<Type>{
		ZVSC_NoEmptyCells.class
	};


    public List<ZV_GamePlayer__c> attachPlayers (List<ZV_Game__C> gameList) {
    	List<ZV_GamePlayer__c> gamePlayerList = new List<ZV_GamePlayer__c>();
    	for (ZV_Game__C game : gameList) {
    		gamePlayerList.addAll(this.attachPlayers(game));
    	} 
    	return gamePlayerList;
    }
    
    private List<ZV_GamePlayer__c> attachPlayers (ZV_Game__C game) {
    	List<ZV_GamePlayer__c> gamePlayerList = new List<ZV_GamePlayer__c>();
    	Boolean humanGoesFirst = this.randomizer.getRandomBoolean();
    	gamePlayerList.add(new ZV_GamePlayer__c(
    		Game__c = game.id,
    		Player__c = playerService.getHumanPlayerId(game),
    		PlayOrder__c = humanGoesFirst ? 1 : 2
    	));
    	  
    	Boolean robotGoesFirst = !humanGoesFirst;
    	gamePlayerList.add(new ZV_GamePlayer__c(
    		Game__c = game.id,
    		Player__c = playerService.getRobotPlayerId(game),
    		PlayOrder__c = robotGoesFirst ? 1 : 2
    	));
    	return gamePlayerList; 
    }
    
    public ZV_GameContext initializePlay(ZV_GameContext gameContext) {
		if (this.playerService.isRobot(gameContext.nextPlayer)) {
    		gameContext.currentGamePlayer = gameContext.nextGamePlayer;
    		gameContext.updatedCellList = this.robotPlayerHelper.maneuver(gameContext);
			this.gamePlayerService.findNextGamePlayer(gameContext);
		}    	
    	return gameContext;
    }
    
	public Boolean canOccupyCell(ZV_GameContext gameContext) {
		Boolean canOccupy = gameContext.cell.Occupant__c == null;
		if (!canOccupy) {
			ZV_Player__c occupant = gameContext.gamePlayerByIdMap.get(gameContext.cell.Occupant__c).Player__r;
			throw new ZVG_TraditionalTicTacToeGameException('Cell is already occupied by ' + occupant.Nickname__c);
		}
		return canOccupy;
	}
	
	public List<ZV_Cell__c> occupyCells(ZV_GameContext gameContext) {
		gameContext.cell.Occupant__c = gameContext.gamePlayerByUserIdMap.get(gameContext.userId).Id;
		return new List<ZV_Cell__c>{gameContext.cell};
	}
	 
	public Id checkForWinner(ZV_GameContext gameContext) {
		return this.victoryConditionHelper.checkForWinner(VICTORY_CONDITION_LIST, gameContext); 
	}
	
	public Boolean checkForStalemate(ZV_GameContext gameContext) {
		return this.stalemateConditionHelper.checkForStalemate(STALEMATE_CONDITION_LIST, gameContext); 
	}    
}