src/objects/ZV_Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Stalemate</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_GameStatusHelper.cls
public class ZV_GameStatusHelper {
	public static String NEW_GAME = 'New';
	public static String IN_PROGRESS = 'In Progress';
	public static String GAME_WON = 'Won';
	public static String STALEMATE = 'Stalemate';
    
    public Boolean isNew(ZV_Game__c game) {
    	return game.Status__c == NEW_GAME;
    }

    public Boolean isInProgress(ZV_Game__c game) {
    	return game.Status__c == IN_PROGRESS;
    }

    public Boolean isWon(ZV_Game__c game) {
    	return game.Status__c == GAME_WON;
    }

    public Boolean isStalemate(ZV_Game__c game) {
    	return game.Status__c == STALEMATE;
    }
}