src/objects/ZV_GamePlayer__c.object
<CustomObject>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>ZV_Game__c</referenceTo>
        <relationshipLabel>Game Players</relationshipLabel>
        <relationshipName>Game_Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PlayOrder__c</fullName>
        <label>Play Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>ZV_Player__c</referenceTo>
        <relationshipLabel>Game Players</relationshipLabel>
        <relationshipName>Game_Players</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game Player</label>
    <nameField>
        <displayFormat>ZVGP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZV_GamePlayerSelector.cls
public with sharing class ZV_GamePlayerSelector extends fflib_SObjectSelector {
	ZV_GameSelector gameSelector;
	ZV_PlayerSelector playerSelector;
	
	public ZV_GamePlayerSelector(ZV_GameSelector gameSelector, ZV_PlayerSelector playerSelector) {
		this.gameSelector = gameSelector;
		this.playerSelector = playerSelector;
	}
 
	public ZV_GamePlayerSelector() {
		this(new ZV_GameSelector(), new ZV_PlayerSelector());
	}
	
	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
			ZV_GamePlayer__c.Id,
			ZV_GamePlayer__c.Game__c,
			ZV_GamePlayer__c.Player__c,
			ZV_GamePlayer__c.PlayOrder__c
		};
	}
 
	public Schema.SObjectType getSObjectType() {
		return ZV_GamePlayer__c.sObjectType;
	} 

	public override String getOrderBy() {
		return 'PlayOrder__c ASC';
	}

	public List<ZV_GamePlayer__c> selectById(Set<Id> idSet) {
		return (List<ZV_GamePlayer__c>) selectSObjectsById(idSet);
	}

	// It is tempting to bulkify this to handle Set<Id> gameIdSet.
	// However, presently this is only consumed by BoardAuraCtrl, when we only need to handle one game at a time.
	// Separating the games back out adds unnecessary/undesirable complexity.
	public List<ZV_GamePlayer__c> selectByGameId(Id gameId) {
		fflib_QueryFactory gamePlayerQueryFactory = newQueryFactory();
		this.gameSelector.configureQueryFactoryFields(gamePlayerQueryFactory, 'Game__c');
		this.playerSelector.configureQueryFactoryFields(gamePlayerQueryFactory, 'Player__c');

		return (List<ZV_GamePlayer__c>) Database.query(
			gamePlayerQueryFactory
				.setCondition('Game__c = :gameId')
				.toSOQL()
		);
	}
}