src/objects/ZV_Game__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Stalemate</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Winner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Winner</label>
        <referenceTo>ZV_Player__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>ZVG-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ZV_GamePlayer__c.object
<CustomObject>
    <fields>
        <fullName>PlayOrder__c</fullName>
        <label>Play Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Game Player</label>
    <nameField>
        <displayFormat>ZVGP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Game Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ZV_GameService.cls
public class ZV_GameService {  
	F45_DML_GenericDml genericDml; 
	ZV_PlayerService playerService;
	ZVG_GameLookup gameLookup;
	ZVR_RobotPlayerHelper robotPlayerHelper;

	public ZV_GameService(
			F45_DML_GenericDml genericDml, 
			ZV_PlayerService playerService, 
			ZVG_GameLookup gameLookup,
			ZVR_RobotPlayerHelper robotPlayerHelper
		) { 
		this.genericDml = genericDml;
		this.playerService = playerService;
		this.gameLookup = gameLookup;
		this.robotPlayerHelper = robotPlayerHelper;
	}

	public ZV_GameService() {
		this(
			new F45_DML_GenericDml(),  
			new ZV_PlayerService(),
			new ZVG_GameLookup(),
			new ZVR_RobotPlayerHelper()
		);
	}		
	
    public ZV_CellOccupyResult reactToOccupiedCell(ZV_GameContext gameContext) {
    	if (this.noGameWinner(gameContext)) {
			this.updateNextPlayer(gameContext);

			while(
					this.noGameWinner(gameContext)
					&& this.playerService.isRobot(gameContext.nextPlayer) 
				) {
	    		gameContext.currentGamePlayer = gameContext.nextGamePlayer;
	    		gameContext.updatedCellList.addAll(this.robotPlayerHelper.maneuver(gameContext));
	    		this.updateNextPlayer(gameContext);
			}
    	} 

		this.genericDml.doUpsert(gameContext.updatedCellList);    	  
		this.genericDml.doUpdate(new List<ZV_Game__c>{gameContext.game});
		return new ZV_CellOccupyResult(gameContext.updatedCellList, gameContext.game); 
    }

    private ZV_GamePlayer__c updateNextPlayer(ZV_GameContext gameContext) {
    	ZV_GamePlayer__c currentNextPlayer = gameContext.nextGamePlayer;
    	Decimal currentPlayOrderValue = currentNextPlayer.PlayOrder__c;
    	
    	List<Decimal> availablePlayOrderValueList = new List<Decimal>(gameContext.gamePlayerByOrderMap.keySet()); 
    	availablePlayOrderValueList.sort();

		// We use the maximum to avoid looping through a large list of players.
    	Decimal maximum = availablePlayOrderValueList[availablePlayOrderValueList.size() - 1]; 
    	Decimal newPlayOrderValue = (currentPlayOrderValue == maximum) 
    		? availablePlayOrderValueList[0]
    		: findNewPlayOrderValue(availablePlayOrderValueList, currentPlayOrderValue);
    	
    	ZV_GamePlayer__c newNextPlayer = (ZV_GamePlayer__c) gameContext.gamePlayerByOrderMap.get(newPlayOrderValue);
    	gameContext.game.NextPlayer__c = newNextPlayer.Id;
    	return newNextPlayer; 
    }
    
    private Decimal findNewPlayOrderValue(List<Decimal> availablePlayOrderValueList, Decimal currentPlayOrderValue) {
    	for (Decimal d: availablePlayOrderValueList) {
    		if (d > currentPlayOrderValue) { 
    			return d;
    		}
    	}
    	return availablePlayOrderValueList[0];
    }
    
    public Boolean isInProgress(ZV_GameContext gameContext) {
    	return noGameWinner(gameContext)
    		&& noStalemate(gameContext);
    }
    
    private Boolean noGameWinner(ZV_GameContext gameContext) {
    	this.gameLookup.getFor(gameContext.game).checkForWinner(gameContext);
    	return gameContext.game.Winner__c == null;
    } 
     
    private Boolean noStalemate(ZV_GameContext gameContext) {
    	this.gameLookup.getFor(gameContext.game).checkForStalemate(gameContext);
    	return gameContext.game.Status__c == 'Stalemate';
    } 
}