src/objects/ZV_Player__c.object
<CustomObject>
    <fields>
        <fullName>IconName__c</fullName>
        <label>Icon Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IconVariant__c</fullName>
        <label>Icon Variant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StrategyClassName__c</fullName>
        <label>Strategy Class Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Player</label>
    <nameField>
        <displayFormat>ZVP-{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Player Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZV_PlayerSelector.cls
public with sharing class ZV_PlayerSelector extends fflib_SObjectSelector { 
	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
			ZV_Player__c.Id, 
			ZV_Player__c.IconName__c,
			ZV_Player__c.IconVariant__c,
			ZV_Player__c.StrategyClassName__c,
			ZV_Player__c.User__c 
		};
	}

	public Schema.SObjectType getSObjectType() {
		return ZV_Player__c.sObjectType;
	} 

	public List<ZV_Player__c> selectById(Set<Id> idSet) {
		return (List<ZV_Player__c>) selectSObjectsById(idSet);
	}

	public List<ZV_Player__c> selectByUserIdOrStrategyName(Set<Id> humanPlayerUserIdSet, Set<String> robotStrategySet) {
		return (List<ZV_Player__c>) Database.query(
			newQueryFactory()
				.setCondition('User__c IN :humanPlayerUserIdSet OR StrategyClassName__c IN :robotStrategySet')
				.toSOQL()		
		);
	}
}